name: Test and upload .jar-file

on: push

jobs:
 testingUploading:
  runs-on: ubuntu-latest
  name: Testing and uploading
  steps:
   - uses: actions/checkout@v2
   - uses: actions/setup-java@v1
     with:
      java-version: '11'
   - name: Build, test and package app
     run: mvn -f pom.xml package
   - name: Show contents of current directory
     run: ls -la
   - uses: actions/upload-artifact@v2
     with:
      name: zipWithJar
      path: ./target/spring-github-actions-demo-0.1.jar
